test: added logs

diff --git a/.tekton/tasks/echo-env.yaml b/.tekton/tasks/echo-env.yaml
--- a/.tekton/tasks/echo-env.yaml
+++ b/.tekton/tasks/echo-env.yaml
@@ -4,6 +4,8 @@ metadata:
   name: echo-env
 spec:
   params:
+    - name: target-branch
+      value: $(params.target-branch)
     - name: node-version
       value: $(params.node-version)
     - name: npm-version
@@ -23,13 +25,22 @@ spec:
       script: |
         #!/bin/bash
         ARTIFACTS_PATH="$(workspaces.output.path)"
+        echo "Listing current directory contents before cd:"
+        ls -la
         cd $ARTIFACTS_PATH
 
         echo "path: $ARTIFACTS_PATH"
 
         if [ "$(params.prerelease)" == "true" ]; then
-          chmod +x ./.tekton/install-prerelease.sh
-          ./.tekton/install-prerelease.sh "$(params.prerelease-node-version)"
+          echo "Checking for ./.tekton/install-prerelease.sh"
+          ls -la ./.tekton
+          if [ -f ./.tekton/install-prerelease.sh ]; then
+            chmod +x ./.tekton/install-prerelease.sh
+            ./.tekton/install-prerelease.sh "$(params.prerelease-node-version)"
+          else
+            echo "Error: ./.tekton/install-prerelease.sh not found."
+            exit 1
+          fi
         fi
 
         echo "Node: $(node --version)"
