chore: update install yaml

diff --git a/.tekton/tasks/install-npm-dependencies.yaml b/.tekton/tasks/install-npm-dependencies.yaml
--- a/.tekton/tasks/install-npm-dependencies.yaml
+++ b/.tekton/tasks/install-npm-dependencies.yaml
@@ -47,7 +47,32 @@ spec:
         # While trying to install node modules with latest prerelease versions, we are running into problems with some packages
         # so changing the order of node version switch to avoid the issues
         if [ -n "$(params.prerelease)" ]; then
-          ./../install-node.sh $(params.node-version) $(params.prerelease-node-version)
+
+          echo "Installing node prerelease version $PRERELEASE_NODE_VERSION.."
+
+          if ! command -v nvm &> /dev/null; then
+            echo "NVM not found. Installing NVM..."
+            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
+
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+          else
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+          fi
+
+          NVM_NODEJS_ORG_MIRROR="https://nodejs.org/download/rc" nvm install "$PRERELEASE_NODE_VERSION" 
+
+          if ! nvm ls "$PRERELEASE_NODE_VERSION" >/dev/null; then
+            echo "RC installation failed for Node.js version $PRERELEASE_NODE_VERSION."
+
+            NVM_NODEJS_ORG_MIRROR="https://nodejs.org/download/nightly" nvm install "$PRERELEASE_NODE_VERSION" || \
+            echo "Installation failed with NIGHTLY mirror"
+          fi
+
+          nvm use "$PRERELEASE_NODE_VERSION"
+
+          echo "Currently using node: $(node --version)"
         fi
 
         if [ "$(params.skip-cache)" == "true" ]; then
