ci: check mysql
[ci skip]

diff --git a/.tekton/git-pr-pipeline.yaml b/.tekton/git-pr-pipeline.yaml
--- a/.tekton/git-pr-pipeline.yaml
+++ b/.tekton/git-pr-pipeline.yaml
@@ -61,6 +61,16 @@ spec:
     - name: start-mysql
       taskRef:
         name: start-mysql-server
+    - name: check-mysql
+      image: ubuntu
+      script:
+        - apt-get update && apt-get install -y netcat
+        - if nc -z -v -w5 mysql 3306; then
+            echo "MySQL connection successful!";
+          else
+            echo "MySQL connection failed!";
+            exit 1;
+          fi
 
 ---
 
