ci: side cars
[ci skip]

diff --git a/.tekton/mysql-task.yaml b/.tekton/mysql-task.yaml
--- a/.tekton/mysql-task.yaml
+++ b/.tekton/mysql-task.yaml
@@ -3,7 +3,7 @@ kind: Task
 metadata:
   name: start-mysql-server
 spec:
-  steps:
+  sidecars:
     - name: start-mysql
       image: mysql:8.0.1
       env:
@@ -16,4 +16,17 @@ spec:
         - name: MYSQL_PASSWORD
           value: nodepw
         - name: MYSQL_ROOT_HOST
-          value: 0.0.0.0
+          value: 0.0.0.0      
+  steps:
+    - name: ping-port
+      image: ubuntu
+      script: |
+        #!/bin/bash
+        apt-get update && apt-get install -y netcat
+
+        if nc -z -v -w5 mysql 3306; then
+          echo "MySQL connection successful!";
+        else
+          echo "MySQL connection failed!";
+          exit 1;
+        fi
